# Generated by Django 4.1.4 on 2022-12-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_info_email_alter_info_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='pgn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ringnum', models.IntegerField(blank=True, null=True)),
                ('egg', models.CharField(max_length=5)),
                ('eggnum', models.CharField(max_length=2)),
                ('eggday', models.DateField(null=True)),
                ('childay', models.DateField(null=True)),
                ('homenum', models.IntegerField(blank=True, null=True)),
                ('roomnum', models.IntegerField(blank=True, null=True)),
                ('nurseringnum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='info',
        ),
    ]
